"""add cover_image to posts

Revision ID: 0c480b004e93
Revises: c08ae243cf99
Create Date: 2026-07-29 15:59:57.934780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c480b004e93'
down_revision: Union[str, None] = 'c08ae243cf99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('cover_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'cover_image')
    # ### end Alembic commands ###
