"""add view_count to posts

Revision ID: 30a2f9779f86
Revises: 3e63861e1d92
Create Date: 2026-07-31 14:21:07.588154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a2f9779f86'
down_revision: Union[str, None] = '3e63861e1d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'view_count')
    # ### end Alembic commands ###
