"""add_follows_table

Revision ID: 8b594acd7c32
Revises: f539837c22e8
Create Date: 2026-07-28 09:47:02.815537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b594acd7c32'
down_revision: Union[str, None] = 'f539837c22e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('follower_id', sa.String(), nullable=False),
    sa.Column('following_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uix_follower_following')
    )
    op.create_index(op.f('ix_follow_id'), 'follow', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follow_id'), table_name='follow')
    op.drop_table('follow')
    # ### end Alembic commands ###
